### ISSUE TITLE
Not an editor command: ZettelNew

### ISSUE THREAD

**Issue by Andreilys** [michal-h21/vim-zettel#35]
So I have this plugin installed
<img width="216" alt="Screen Shot 2020-03-28 at 8 11 40 PM" src="https://user-images.githubusercontent.com/8299248/77839319-56fcd300-7130-11ea-8ac1-e743df6af3e3.png">

But whenever I try to use the `:ZettelNew` command in either plain vim or within vimWikiIndex, I get "Not an editor command: ZettelNew"

Is there additional configuration that I need to add to make this work? 

<img width="765" alt="Screen Shot 2020-03-28 at 8 13 29 PM" src="https://user-images.githubusercontent.com/8299248/77839344-988d7e00-7130-11ea-9eba-157868b9a6e0.png">

**Comment by sunnyrahul25** [comment]
Not sure but may be vimwiki is not setup.
did you add the configuration
let g:vimwiki_list = [{'path':'~/scratchbox/vimwiki/markdown/','ext':'.md','syntax':'markdown'}, {"path":"~/scratchbox/vimwiki/wiki/"}]
to vimrc?

**Comment by ecks** [comment]
keep in mind you also need to have a file open that has the same extension as as what you define in your vimwiki config. For instance, if you are using markdown, you will need to have a markdown file open. The reason for this is that ZettelNew will only be available on the correct filetype, since its in ftplugin.

**Comment by Andreilys** [comment]
Thanks @ecks that explains it, I have an alias command now to create Zettel's.

alias z="vim test.md +ZettelNew"
